=== ChrisC132/Adaptive-Channels-for-TS3-Servers/src/main/java/TSConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="AdaptiveChannelsConfig">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="TSInfo">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="TSHost" type="xsd:string"/>
                            <xsd:element name="LoginInfo">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Username" type="xsd:string"/>
                                        <xsd:element name="Password" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="BotNickname" type="xsd:string"/>
                            <xsd:element name="TSPort" type="xsd:int" minOccurs="0" maxOccurs="1"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="ChannelInfo">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Channel" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="ParentChannelID" type="xsd:int"/>
                                        <xsd:element name="MainChannelID" type="xsd:int"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="ChannelName" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="Spacer" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Top" type="xsd:string"/>
                            <xsd:element name="Middle" type="xsd:string"/>
                            <xsd:element name="Bottom" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== ChrisC132/Adaptive-Channels-for-TS3-Servers/example/TSConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<AdaptiveChannelsConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TSConfig.xsd">
    <TSInfo>
        <TSHost>TeamSpeak Hostname</TSHost>
        <LoginInfo>
            <Username>Admin Username</Username>
            <Password>Admin Password</Password>
        </LoginInfo>
        <BotNickname>Name of the Bot</BotNickname>
        <TSPort>1234</TSPort>
    </TSInfo>
    <ChannelInfo>
        <Channel ChannelName="Channel 1">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>43</MainChannelID>
        </Channel>
        <Channel ChannelName="Channel 2">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>891</MainChannelID>
        </Channel>
    </ChannelInfo>
    <Spacer>
        <Top>┏</Top>
        <Middle>┣</Middle>
        <Bottom>┗</Bottom>
    </Spacer>
</AdaptiveChannelsConfig>

=== ChrisC132/Adaptive-Channels-for-TS3-Servers/src/main/java/TSConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<AdaptiveChannelsConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TSConfig.xsd">
    <TSInfo>
        <TSHost>fugri.de</TSHost>
        <LoginInfo>
            <Username>serveradmin</Username>
            <Password>***REMOVED***</Password>
        </LoginInfo>
        <BotNickname>FugriBot</BotNickname>
    </TSInfo>
    <ChannelInfo>
        <Channel ChannelName="TalkZuZweit">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>43</MainChannelID>
        </Channel>
        <Channel ChannelName="TalkZuDritt">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>891</MainChannelID>
        </Channel>
        <Channel ChannelName="TalkZuViert">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>2010</MainChannelID>
        </Channel>
        <Channel ChannelName="TalkZuFÃ¼nft">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>1344</MainChannelID>
        </Channel>
        <Channel ChannelName="TalkZuSechst">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>2092</MainChannelID>
        </Channel>
        <Channel ChannelName="Treff">
            <ParentChannelID>10</ParentChannelID>
            <MainChannelID>11</MainChannelID>
        </Channel>
        <Channel ChannelName="VIP">
            <ParentChannelID>7</ParentChannelID>
            <MainChannelID>640</MainChannelID>
        </Channel>
        <Channel ChannelName="Supporter">
            <ParentChannelID>7</ParentChannelID>
            <MainChannelID>230</MainChannelID>
        </Channel>
    </ChannelInfo>
</AdaptiveChannelsConfig>
